name: Bug report
description: Something is not working as expected
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug!

        Tip: logs are written to `~/Library/Logs/BC64Keys/bc64keys-status.log`.

  - type: input
    id: macos
    attributes:
      label: macOS version
      placeholder: "e.g. 14.3"
    validations:
      required: true

  - type: input
    id: app_version
    attributes:
      label: App version
      placeholder: "e.g. 1.0.0 (from Info.plist or release tag)"
    validations:
      required: false

  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: Describe the bug clearly.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs (optional)
      description: Paste relevant lines from `~/Library/Logs/BC64Keys/bc64keys-status.log`.
      render: shell
    validations:
      required: false
